### ISSUE TITLE
The altitude in RTTY strings is set by "altmax" variable?

### ISSUE THREAD

**Issue by rossengeorgiev** [HABduino/HABduino#12]
This code:
https://github.com/HABduino/HABduino/blob/4f761bcb3b1ebe6875d95b780ed67466d98a066d/Software/habduino/habduino.ino#L340-L357

Not sure if that's intended or a bug.

**Comment by hexameron** [comment]
It is a good feature. "altmax" is reset to zero after every sentence, so Habduino reports the highest altitude at burst. The downside is that the altitude graph clamps to zero when gps lock is <4 sats.
It might be an idea to have a "last_good_altmax" variable to use when altmax is zero.

**Comment by rossengeorgiev** [comment]
I'm confused. So, it doesn't record the max achieved altitude, instead is the max altitude received from the gps between transmissions. That's a strange behavior. You could end up in a situation where you get coordinates from the last gps sentence, but the altitude from a sentence before that, which had a higher altitude. Also, you get altitude 0 if there was no lock between transmissions.

Another situation is getting a couple of good positions, and just before you transmit you get a `sat < 4`. You will just send some altitude and `0,0`. Perhaps that's the purpose behind it, but it's seems confusing.

**Comment by hexameron** [comment]
You could check the logs, but I think thats what Habduino was doing the last time it flew. Upu uses the same code on his Pava trackers, but they don`t seem to lose GPS lock so it is not an issue there.

**Comment by hexameron** [comment]
I was remembering that wrong. The Habduino flight was sending Altitude with no Position. I don`t understand that.

**Comment by Upuaut** [comment]
Gosh :) Ok that code is a hang over from the days when we were chasing altitude records. As the radio transmission was interrupt driven the GPS could happily be interrogated 15 times in the time it took to transmit a sentenced @ 50 baud.In that 15 seconds it could have achieved its maximum altitude and burst. obviously when it bursts it drops pretty quickly. 

At time there was only 50 meters in the record so the code reports the maximum altitude achieved since the last string was transmitted. Once transmitted it just resets and starts the cycle again. 

So to clarify it only reports the maximum altitude achieved during one telemetry transmission. You are correct it could result in a altitude from one location report with the coordinates from another but in reality this doesn't matter. If there is no lock (unusual) the code should report 0,0,0 anyway. 

Hope this confirms the behaviour, its probably not needed but people like to know exactly how high they got.
